DATA PREPROCESSING FOR POWER BI TIMELINE ANALYSIS
AUTHOR - SOUMITH VARMA KUSAMPUDI

In [22]:
#importing libraries
import pandas as pd

In [23]:
#importing dataset 
dataf = pd.read_csv('covid.csv')

In [24]:
dataf.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [25]:
#Displaying columns
dataf.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [26]:
print(dataf.isnull().sum())

iso_code                                        0
continent                                    9553
location                                        0
date                                            0
total_cases                                  2871
                                            ...
human_development_index                     28664
excess_mortality_cumulative_absolute       153633
excess_mortality_cumulative                153633
excess_mortality                           153633
excess_mortality_cumulative_per_million    153633
Length: 67, dtype: int64

In [11]:
print(dataf.isnull().sum())

iso_code                          0
continent                      9553
location                          0
date                              0
total_cases                    2871
new_cases                      2918
total_deaths                  20418
new_deaths                    20251
reproduction_rate             38942
stringency_index              34397
population                     1044
population_density            17482
median_age                    27117
aged_65_older                 28549
aged_70_older                 27825
gdp_per_capita                26503
extreme_poverty               71718
cardiovasc_death_rate         28139
diabetes_prevalence           21278
handwashing_facilities        93496
hospital_beds_per_thousand    40664
life_expectancy               10597
human_development_index       28664
dtype: int64

In [27]:
#handling missing data
dataf['continent'].fillna(dataf['location'],inplace=True)
dataf['total_cases'].fillna(0,inplace=True)
dataf['new_cases'].fillna(0,inplace=True)
dataf['total_deaths'].fillna(0,inplace=True)
dataf['new_deaths'].fillna(0,inplace=True)
dataf['reproduction_rate'].fillna(round(dataf['reproduction_rate'].mean(),2),inplace=True)
dataf['stringency_index'].fillna(round(dataf['stringency_index'].mean(),2),inplace=True)
dataf['population'].fillna(round(dataf['population'].mean(),2),inplace=True)
dataf['population_density'].fillna(round(dataf['population_density'].mean(),2),inplace=True)
dataf['median_age'].fillna(round(dataf['median_age'].median(),2),inplace=True)
dataf['aged_65_older'].fillna(round(dataf['aged_65_older'].mean(),2),inplace=True)
dataf['aged_70_older'].fillna(round(dataf['aged_70_older'].mean(),2),inplace=True)
dataf['gdp_per_capita'].fillna(round(dataf['gdp_per_capita'].mean(),2),inplace=True)
dataf['extreme_poverty'].fillna(round(dataf['extreme_poverty'].mean(),2),inplace=True)
dataf['cardiovasc_death_rate'].fillna(round(dataf['cardiovasc_death_rate'].mean(),2),inplace=True)
dataf['diabetes_prevalence'].fillna(round(dataf['diabetes_prevalence'].mean(),2),inplace=True)
dataf['handwashing_facilities'].fillna(round(dataf['handwashing_facilities'].mean(),2),inplace=True)
dataf['hospital_beds_per_thousand'].fillna(round(dataf['hospital_beds_per_thousand'].mean(),2),inplace=True)
dataf['life_expectancy'].fillna(round(dataf['life_expectancy'].mean(),2),inplace=True)
dataf['human_development_index'].fillna(round(dataf['human_development_index'].mean(),2),inplace=True)

In [13]:
print(dataf.isnull().sum())

iso_code                      0
continent                     0
location                      0
date                          0
total_cases                   0
new_cases                     0
total_deaths                  0
new_deaths                    0
reproduction_rate             0
stringency_index              0
population                    0
population_density            0
median_age                    0
aged_65_older                 0
aged_70_older                 0
gdp_per_capita                0
extreme_poverty               0
cardiovasc_death_rate         0
diabetes_prevalence           0
handwashing_facilities        0
hospital_beds_per_thousand    0
life_expectancy               0
human_development_index       0
dtype: int64

In [28]:
dataf['date'] = pd.to_datetime(dataf['date'])
dataf['Month-Year'] = dataf['date'].dt.strftime('%b-%Y')

In [29]:
dataf.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million,Month-Year
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,Feb-2020
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,Feb-2020
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,Feb-2020
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,Feb-2020
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,Feb-2020

In [21]:
dataf.to_csv('Final covid data.csv')